const supportedBanks = [
  {
    code: "boa",
    color: "#EFF1ED",
    official_name: "Bank of America",
    name: "Bank of America",
  },
  {
    code: "wfg",
    color: "#EFF1ED",
    official_name: "Wells Fargo",
    name: "Wells Fargo",
  },
  {
    code: "jpm",
    color: "#EFF1ED",
    official_name: "JPMorgan Chase",
    name: "Chase Bank",
  },
  {
    code: "citi",
    color: "#EFF1ED",
    official_name: "CITIGROUP INC",
    name: "Citibank",
  },
  {
    code: "cpone",
    color: "#EFF1ED",
    official_name: "Capital One",
    name: "Capital One",
  },
  {
    code: "pnc",
    color: "#EFF1ED",
    official_name: "PNC Financial Services",
    name: "PNC Financial Services",
  },
  {
    code: "mgs",
    color: "#EFF1ED",
    official_name: "Morgan Stanley",
    name: "Morgan Stanley",
  },
  {
    code: "gsachs",
    color: "#EFF1ED",
    official_name: "Goldman Sachs",
    name: "Goldman Sachs",
  },
  {
    code: "usbcorp",
    color: "#EFF1ED",
    official_name: "US Bancorp",
    name: "US Bancorp",
  },
  {
    code: "tfc",
    color: "#EFF1ED",
    official_name: "Truist Financial",
    name: "Truist Financial",
  },
  {
    code: "hsbc",
    color: "#EFF1ED",
    official_name: "HSBC Bank USA",
    name: "HSBC Bank USA",
  },
  {
    code: "ssc",
    color: "#EFF1ED",
    official_name: "State Street Corporation",
    name: "State Street Corporation",
  },
  {
    code: "tdb",
    color: "#EFF1ED",
    official_name: "TD Bank",
    name: "TD Bank",
  },
  {
    code: "bbva",
    color: "#EFF1ED",
    official_name: "BBVA USA",
    name: "BBVA USA",
  },
  {
    code: "bny",
    color: "#EFF1ED",
    official_name: "Bank of New York",
    name: "Bank of New York",
  },
  {
    code: "cfg",
    color: "#EFF1ED",
    official_name: "Citizens Financial Group",
    name: "Citizens Financial Group",
  },
  {
    code: "rgb",
    color: "#EFF1ED",
    official_name: "Region Bank",
    name: "Region Bank",
  },
  {
    code: "kyb",
    color: "#EFF1ED",
    official_name: "KeyBank",
    name: "KeyBank",
  },
  {
    code: "cshwb",
    color: "#EFF1ED",
    official_name: "Charles Schwab Bank",
    name: "Charles Schwab Bank",
  },
  {
    code: "ftb",
    color: "#EFF1ED",
    official_name: "Fifth Third Bank",
    name: "Fifth Third Bank",
  },
  {
    code: "bcly",
    color: "#EFF1ED",
    official_name: "Barclays",
    name: "Barclays",
  },
  {
    code: "abc",
    color: "#EFF1ED",
    official_name: "Associated Banc-Corp",
    name: "Associated Banc-Corp",
  },
];

export default supportedBanks;
